# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('title', models.TextField()),
                ('citations', models.IntegerField()),
                ('abstract', models.TextField()),
                ('journal', models.TextField()),
                ('volume', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='papers',
            field=models.ManyToManyField(to='scraper.Paper'),
        ),
    ]
