# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_project_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundedAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='paper',
            options={'ordering': ['year', 'title']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['year', 'title']},
        ),
        migrations.AlterField(
            model_name='project',
            name='researcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.FundedAuthor'),
        ),
    ]
